import { Poppins, Inter } from 'next/font/google'
import '@/app/globals.css'
import Dock from '@/components/Dock'

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700'],
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className={`${poppins.variable} ${inter.variable} antialiased`} lang="en">
      <body>
        {children}
        <Dock />
      </body>
    </html>
  )
}
